name: pyLint

on: push

jobs:
  linting_and_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python with caching
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install Lint & Formatting Libraries (including BasedPyright)
        run: |
          pip install autopep8 autoflake isort black basedpyright setuptools
          pip install -r requirements.txt

      - name: Run BasedPyright (Reports all errors in annotations)
        run: |
          basedpyright . || true
          
      - name: Check for showstoppers (autopep8)
        run: autopep8 --verbose --in-place --recursive --aggressive --aggressive .
      
      - name: Remove unused imports and variables (autoflake)
        run: autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .
      
      - name: lint with isort and black
        run: |
          isort bot
          black --fast bot
          
      # commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'pyLint: auto-fixes'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: Nubuki-all
          commit_user_email: 121189493+Nubuki-all@users.noreply.github.com
          commit_author: Nubuki-all <121189493+Nubuki-all@users.noreply.github.com>

